apiVersion: metal3.io.sigs.k8s.io/v1alpha1
kind: HardwareClassificationController
metadata:
  name: hardwareclassificationcontroller-sample
spec:
  # Add fields here
  namespace: metal3
  expectedValidationConfiguration:
        - profileName: Profile 1
          expectedCPU:
                count: 4
          expectedDisk:
                sizeBytesGB: 25
                numberOfDisks: 2
          expectedNICS:
                numberOfNICS: 4
          expectedRAM: 8
          expectedSystemVendor:
                name: Dell Inc.
        - profileName: Profile 2
          expectedCPU:
                count: 8
          expectedDisk:
                sizeBytesGB: 50
                numberOfDisks: 4
          expectedNICS:
                numberOfNICS: 8
          expectedRAM: 16
          expectedSystemVendor:
                name: Dell Inc.
