apiVersion: metal3.io.sigs.k8s.io/v1alpha1
kind: HardwareClassificationController
metadata:
  name: hardwareclassificationcontroller-sample
spec:
  expectedValidationConfiguration:
      namespace: metal3
      CPU:
        minimumCount: 4
        maximumCount: 6
        minimumSpeed: "2.7"
      Disk:
        minimumCount: 2
        minimumIndividualSize: 2200
      RAM:
        minimumSizeGB: 6        
      NIC:
         minimumCount: 1
         
